application: phpshradhand
version: 2
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  
# Serve CSS.
- url: /stylesheets
  static_dir: stylesheets

# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /
  script: main.php
  
- url: /busreis
  script: Busreis.php
  
- url: /kerstboom
  script: Kerstboom.php
  
- url: /zwemclubs
  script: Zwemclubs.php
  
- url: /kapperszaak
  script: Kapperszaak.php
  
- url: /webshop
  script: Webshop.php
  
- url: /functies
  script: Functies.php